-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://ithub.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here
